name: Glovo Order Automation

on:
  schedule:
    # Run every 5 minutes (for testing)
    # - cron: '*/5 * * * *'

    # Run every day at 07:00 AM UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'step_2_quota_Config/**'
      - 'step_3_send_order_with_quotaID/**'
      - 'production_workflow.py'

jobs:
  glovo-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Google Sheets credentials
      run: |
        echo '${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}' > google_sheets_credentials.json
        
    - name: Run Glovo Order Automation
      env:
        GLOVO_CLIENT_ID: ${{ secrets.GLOVO
