name: Test Daily Delivery Automation

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: true
        type: boolean

jobs:
  test-automation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Test imports
      run: |
        python -c "import requests, pandas, openpyxl, gspread; print('✅ All imports successful')"
        
    - name: Test authentication
      run: |
        cd step_1_authentication
        python token_service.py
        
    - name: Test automation script
      run: |
        python test_github_actions.py
